name: Main Workflow
on: [push]
jobs:
  build:
    name: Build
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [18, 19, 20, 21]
    runs-on: ubuntu-latest
    container: node:${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v4
      - run: node --version
      - run: npm install
        env:
          PUPPETEER_DOWNLOAD_PATH: ~/.npm/chromium
      - run: npm install --only=dev
      - run: npm run lint
      - run: npm test
        env:
          PATH: ~/.npm/chromium
